# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/tututugege"

[social.params]
icon = "brand-github"

[[social]]
identifier = "zhihu"
name = "Zhihu"
url = "https://zhihu.com/people/16-34-73-44"

[social.params]
icon = "brand-zhihu"
